/**
 * @typedef {import('@sveltejs/kit').Cookies} Cookies
 * @typedef {import('../routes/[sessionId]/$types').RouteParams} SessionIdParams
 * 
 * @typedef {import("firebase/database").DatabaseReference} DatabaseReference
 *
 * Possible session states
 * @typedef {'INITIATED'|'STARTED'|'FINISHED'|'LOADING'|'UNKNOWN'} SessionState
 *
 * Possible round states
 * @typedef {'SELECT'|'GUESS'|'MARK'|'GROUP'|'VOTE'|'TALLY'|'LOADING'|'UNKNOWN'} RoundState
 *
 * Inactive player states
 * @typedef {'KICKED'|'OUTSIDER'|'READY'|'LOADING'|'UNKNOWN'} PlayerState
 *
 * Available categories
 * @typedef {'Rare words'|'Scientific names'|'Film taglines'|'Famous people'} Category
 *
 * Session data structure
 * @typedef {Object} Session
 * @property {SessionState} state - Current state of the session
 * @property {string} creator - Username of session creator
 * @property {number} limit - Round limit
 * @property {number} current - Current round
 * @property {number} ais - Number of AI guesses
 * @property {Object<string, boolean>} uids - Allowed user IDs
 * @property {Category[]} categories - Categories included
 * @property {Scoreboard} scoreboard - A mapping between players and their most recent scores
 * @property {Object.<number, Round>} rounds - Round data
 * @property {Object.<string, string>} kicked - Kicked players: kicked as key and kicker as value
 *
 * Round data structure
 * @typedef {Object} Round
 * @property {string} dasher - Username of the dasher for that round
 * @property {string} prompt - prompt
 * @property {string} response - response to the prompt
 * @property {boolean} custom - whether the prompt is custom
 * @property {number} time - Unix timestamp of guess expiry
 * @property {string} interruption - reason for round flow interruption (e.g. everyone guessed correctly)
 * @property {RoundState} state - Current state of the round
 * @property {Category} category - category for the round
 * @property {Object.<string, Guess>} guesses - a key-value pair of guesses where the key is a user and value is the guess
 * @property {Object.<string, string>} votes - a key value pair of guesser and the group they've picked
 *
 * Guess data structure
 * @typedef {Object} Guess
 * @property {string} response - Response to the prompt
 * @property {boolean} correct - Whether the guess was correct
 * @property {boolean} double - double bluff enabled
 * @property {string} group - guess group
 * @property {boolean} automatic - automatic guess generated by AI
 *
 * A mapping between players and their latest aggregate scores
 * @typedef {Object.<string, number>} Scoreboard
 * 
 * Session action processing function
 * @typedef {function(Cookies, SessionIdParams, Request): Promise<void>} SessionAction
 */
export {};
